#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

openapi: "3.0.2"
info:
  x-api-id: ced417b0-5086-472d-bf72-6a2a6ec0dd38
  x-audience: external-public
  description: "Micro Service Chassis"
  version: "0.0.1"
  title: "Micro Service Chassis"
  license:
    name: "COPYRIGHT Ericsson 2021"
    url: "https://www.ericsson.com/en/legal"
  termsOfService: "https://www.ericsson.com/en/legal"
  contact:
    email: "Team Thunderbee<PDLENMCOUN@pdl.internal.ericsson.com>"
tags:
  - name: "sample"
    description: "Sample tag for demo purposes"
paths:
    /v1/sample:
      get:
        tags:
          - "sample"
        summary: "Returns a static response"
        operationId: "sample"
        responses:
          "200":
            description: "OK"
            content:
              application/json:
                schema:
                  type: "string"
          "404":
            description: "Not Found"
          default:
            description: "Internal Server Error"