#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: Service
metadata:
  name: {{ include "eric-oss-common-ci-pocs-test20.fullname" . }}
  labels:
  {{- include "eric-oss-common-ci-pocs-test20.labels" . | nindent 4 }}
  annotations:
  {{- include "eric-oss-common-ci-pocs-test20.annotations-with-prometheus" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | quote }}
  {{- if .Values.global }}
  {{- if .Values.global.internalIPFamily }}
  ipFamilies: [{{ .Values.global.internalIPFamily }}]
  {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      {{- if .Values.global }}
      {{- if .Values.global.security }}
      {{- if .Values.global.security.tls }}
      {{- if .Values.global.security.tls.enabled }}
      name: https-metrics
      {{- end }}
      {{- end }}
      {{- end }}
      {{- else }}
      name: http-metrics
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "eric-oss-common-ci-pocs-test20.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
